// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCartService.Data.Context;

namespace ShoppingCartService.Migrations
{
    [DbContext(typeof(ShoppingCartDbContext))]
    [Migration("20200530183817_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingCartService.Models.ShoppingCartItem", b =>
                {
                    b.Property<Guid>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("CatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShoppingCartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShoppingCartItemId");

                    b.ToTable("ShoppingCartItems");

                    b.HasData(
                        new
                        {
                            ShoppingCartItemId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df811"),
                            Amount = 1,
                            CatalogItemId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df801"),
                            ShoppingCartId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df810")
                        },
                        new
                        {
                            ShoppingCartItemId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df812"),
                            Amount = 1,
                            CatalogItemId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df802"),
                            ShoppingCartId = new Guid("90d6da79-e0e2-4ba8-bf61-2d94d90df810")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
